name: docker-nightly

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Lsky-pro commit tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set hash
        id: vars
        run: |
          sha=$(curl -sX GET \
            "https://api.github.com/repos/lsky-org/lsky-pro/commits/${{github.event.inputs.tag}}" \
            | jq -r '.sha')
          echo "::set-output name=sha::${sha}"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S%:z')"

      - name: Create json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "version.json"
          json: '{"type": "docker", "tag": "latest", "commit": "${{ steps.vars.outputs.sha }}", "date": "${{ steps.date.outputs.date }}"}'
          dir: './'

      - name: Setup platform emulator
        uses: docker/setup-qemu-action@v1
        
      - name: Setup multi-arch docker build
        uses: docker/setup-buildx-action@v1

      - name: Download and Unzip Upstream Source Code
        run: |
          curl -OL https://github.com/lsky-org/lsky-pro/archive/${{ steps.vars.outputs.sha }}.zip
          unzip -o *.zip
          mv ./lsky-pro-${{ steps.vars.outputs.sha }}/* ./
          mv ./lsky-pro-${{ steps.vars.outputs.sha }}/.env.example ./

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Dependencies
        run: composer install --optimize-autoloader

      - name: Clean file to reduce image size
        run: |
          rm -rf ${{ steps.vars.outputs.sha }}.zip lsky-pro-${{ steps.vars.outputs.sha }}
          rm -rf .editorconfig .gitattributes .gitignore .styleci.yml composer.lock package-lock.json README.md tailwind.config.js webpack.mix.js

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64/v8, linux/arm/v7
          push: true
          labels: |
            build_version=TyRoyal version:- ${{github.event.inputs.tag}} nightly Build-date:- ${{steps.date.outputs.date}}
          tags: tyroyal/lsky-pro-x:nightly


